---
name: Update Wiki

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: JoeIzzard/ghaction-wiki-sync@v1
      with:
        username: 14paxton
        access_token: "{{ secrets.SYNC_WIKI_TOKEN }}"
        commit_message: "wikisync"
        commit_username: "14paxton"
        commit_email: "14paxton@gmail.com"
