---
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Wiki Sync
jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Sync Wiki
        uses: joeizzard/action-wiki-sync@master
        with:
          username: 14paxton
          access_token: ${{ secrets.SYNC_WIKI_TOKEN }}
          wiki_folder: wiki
          commit_message: wikisync
          commit_username: 14paxton@gmail.com
          commit_email: 14paxton@gmail.com
